//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrmAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrmAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 StrmAssistant_less 的本地化字符串。
        /// </summary>
        public static string About_Fork {
            get {
                return ResourceManager.GetString("About_Fork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About StrmAssistant Pro 的本地化字符串。
        /// </summary>
        public static string About_StrmAssistant_Pro {
            get {
                return ResourceManager.GetString("About_StrmAssistant_Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutOptions_EditorTitle_About {
            get {
                return ResourceManager.GetString("AboutOptions_EditorTitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you wish to continue? 的本地化字符串。
        /// </summary>
        public static string AreYouSureToContinue {
            get {
                return ResourceManager.GetString("AreYouSureToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 blog url 的本地化字符串。
        /// </summary>
        public static string Blog_Url {
            get {
                return ResourceManager.GetString("Blog_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Episode Refresh 的本地化字符串。
        /// </summary>
        public static string CatchupTask_EpisodeRefresh_EpisodeRefresh {
            get {
                return ResourceManager.GetString("CatchupTask_EpisodeRefresh_EpisodeRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Built-in Intro Detection 的本地化字符串。
        /// </summary>
        public static string CatchupTask_Fingerprint_Fingerprint {
            get {
                return ResourceManager.GetString("CatchupTask_Fingerprint_Fingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior-based Marker Sync 的本地化字符串。
        /// </summary>
        public static string CatchupTask_IntroSkip_IntroSkip {
            get {
                return ResourceManager.GetString("CatchupTask_IntroSkip_IntroSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MediaInfo Extract 的本地化字符串。
        /// </summary>
        public static string CatchupTask_MediaInfo_MediaInfo {
            get {
                return ResourceManager.GetString("CatchupTask_MediaInfo_MediaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clears behavior-based intro and credits markers 的本地化字符串。
        /// </summary>
        public static string ClearChapterMarkersTask_Description_Clears_behavior_based_intro_and_credits_markers {
            get {
                return ResourceManager.GetString("ClearChapterMarkersTask_Description_Clears_behavior_based_intro_and_credits_marke" +
                        "rs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Episode Intros 的本地化字符串。
        /// </summary>
        public static string ClearChapterMarkersTask_Name_Clear_Episode_Intros {
            get {
                return ResourceManager.GetString("ClearChapterMarkersTask_Name_Clear_Episode_Intros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deletes all persons 的本地化字符串。
        /// </summary>
        public static string DeletePersonTask_Description_Deletes_all_persons {
            get {
                return ResourceManager.GetString("DeletePersonTask_Description_Deletes_all_persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disclaimer 的本地化字符串。
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to view the disclaimer. Do not send logs to the official team before uninstalling the plugin. Please remember this! 的本地化字符串。
        /// </summary>
        public static string DisclaimerButtonText {
            get {
                return ResourceManager.GetString("DisclaimerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Episode Name 的本地化字符串。
        /// </summary>
        public static string EpisodeRefreshOption_DefaultEpisodeName_Default_Episode_Name {
            get {
                return ResourceManager.GetString("EpisodeRefreshOption_DefaultEpisodeName_Default_Episode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Image 的本地化字符串。
        /// </summary>
        public static string EpisodeRefreshOption_NoImage_No_Image {
            get {
                return ResourceManager.GetString("EpisodeRefreshOption_NoImage_No_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non Chinese Overview 的本地化字符串。
        /// </summary>
        public static string EpisodeRefreshOption_NonChineseOverview_Non_Chinese_Overview {
            get {
                return ResourceManager.GetString("EpisodeRefreshOption_NonChineseOverview_Non_Chinese_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Overview 的本地化字符串。
        /// </summary>
        public static string EpisodeRefreshOption_NoOverview_No_Overview {
            get {
                return ResourceManager.GetString("EpisodeRefreshOption_NoOverview_No_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace Captured Image 的本地化字符串。
        /// </summary>
        public static string EpisodeRefreshOption_ReplaceCapturedImage_Replace_Captured_Image {
            get {
                return ResourceManager.GetString("EpisodeRefreshOption_ReplaceCapturedImage_Replace_Captured_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh missing metadata and images for episodes by preference 的本地化字符串。
        /// </summary>
        public static string EpisodeRefreshTask_Description_Refresh_metadata_for_episodes_missing_overview {
            get {
                return ResourceManager.GetString("EpisodeRefreshTask_Description_Refresh_metadata_for_episodes_missing_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Catch All Allow 的本地化字符串。
        /// </summary>
        public static string ExclusiveControl_CatchAllAllow_CatchAllAllow {
            get {
                return ResourceManager.GetString("ExclusiveControl_CatchAllAllow_CatchAllAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Catch All Block 的本地化字符串。
        /// </summary>
        public static string ExclusiveControl_CatchAllBlock_CatchAllBlock {
            get {
                return ResourceManager.GetString("ExclusiveControl_CatchAllBlock_CatchAllBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract Alternative Versions on Playback Stop 的本地化字符串。
        /// </summary>
        public static string ExclusiveControl_ExtractAlternative_ExtractAlternative {
            get {
                return ResourceManager.GetString("ExclusiveControl_ExtractAlternative_ExtractAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Extract on File Change 的本地化字符串。
        /// </summary>
        public static string ExclusiveControl_ExtractOnFileChange_ExtractOnFileChange {
            get {
                return ResourceManager.GetString("ExclusiveControl_ExtractOnFileChange_ExtractOnFileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore External Subtitle Change 的本地化字符串。
        /// </summary>
        public static string ExclusiveControl_IgnoreExtSubChange_IgnoreExtSubChange {
            get {
                return ResourceManager.GetString("ExclusiveControl_IgnoreExtSubChange_IgnoreExtSubChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore File Change 的本地化字符串。
        /// </summary>
        public static string ExclusiveControl_IgnoreFileChange_IgnoreFileChange {
            get {
                return ResourceManager.GetString("ExclusiveControl_IgnoreFileChange_IgnoreFileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Intro Marker Protect 的本地化字符串。
        /// </summary>
        public static string ExclusiveControl_NoIntroProtect_NoIntroProtect {
            get {
                return ResourceManager.GetString("ExclusiveControl_NoIntroProtect_NoIntroProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Persist Integration 的本地化字符串。
        /// </summary>
        public static string ExclusiveControl_NoPersistIntegration_NoPersistIntegration {
            get {
                return ResourceManager.GetString("ExclusiveControl_NoPersistIntegration_NoPersistIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Experience Enhance 的本地化字符串。
        /// </summary>
        public static string ExperienceEnhanceOptions_EditorTitle_Experience_Enhance {
            get {
                return ResourceManager.GetString("ExperienceEnhanceOptions_EditorTitle_Experience_Enhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempt to cascade delete the target file of strm or symlink, and the related files and emptry directory. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string ExperienceEnhanceOptions_EnableDeepDelete_Attempt_to_cascade_delete_the_underlying_file_of_strm_or_symlink__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ExperienceEnhanceOptions_EnableDeepDelete_Attempt_to_cascade_delete_the_underlyin" +
                        "g_file_of_strm_or_symlink__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Deep Delete 的本地化字符串。
        /// </summary>
        public static string ExperienceEnhanceOptions_EnableDeepDelete_Enable_Deep_Delete {
            get {
                return ResourceManager.GetString("ExperienceEnhanceOptions_EnableDeepDelete_Enable_Deep_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notification Enhanced 的本地化字符串。
        /// </summary>
        public static string ExperienceEnhanceOptions_EnhanceNotification_Enhance_Notification {
            get {
                return ResourceManager.GetString("ExperienceEnhanceOptions_EnhanceNotification_Enhance_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show episode details in add/remove series group notification, provide deep delete notification. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string ExperienceEnhanceOptions_EnhanceNotification_Show_episode_details_in_series_notification__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ExperienceEnhanceOptions_EnhanceNotification_Show_episode_details_in_series_notif" +
                        "ication__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Movie Merge Preference 的本地化字符串。
        /// </summary>
        public static string ExperienceEnhanceOptions_MergeMoviePreferences_Movie_Merge_Preference {
            get {
                return ResourceManager.GetString("ExperienceEnhanceOptions_MergeMoviePreferences_Movie_Merge_Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TV Series Merge Preference 的本地化字符串。
        /// </summary>
        public static string ExperienceEnhanceOptions_MergeSeriesPreferences_Series_Merge_Preference {
            get {
                return ResourceManager.GetString("ExperienceEnhanceOptions_MergeSeriesPreferences_Series_Merge_Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split multi-version movies in all libraries (scan library for TV Series split) 的本地化字符串。
        /// </summary>
        public static string ExperienceEnhanceOptions_SplitMovieButton_Split_multi_version_movies_in_all_libraries {
            get {
                return ResourceManager.GetString("ExperienceEnhanceOptions_SplitMovieButton_Split_multi_version_movies_in_all_libra" +
                        "ries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin names separated by comma or semicolon like MovieDb,Tvdb. Default is BLANK. 的本地化字符串。
        /// </summary>
        public static string ExperienceEnhanceOptions_SuppressPluginUpdates_Plugin_names_separated_by_comma_or_semicolon_like_MovieDb_Tvdb__Default_is_BLANK_ {
            get {
                return ResourceManager.GetString("ExperienceEnhanceOptions_SuppressPluginUpdates_Plugin_names_separated_by_comma_or" +
                        "_semicolon_like_MovieDb_Tvdb__Default_is_BLANK_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suppress Plugin Auto Updates 的本地化字符串。
        /// </summary>
        public static string ExperienceEnhanceOptions_SuppressPluginUpdates_Suppress_Auto_Plugin_Updates {
            get {
                return ResourceManager.GetString("ExperienceEnhanceOptions_SuppressPluginUpdates_Suppress_Auto_Plugin_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracts intro fingerprint from episodes 的本地化字符串。
        /// </summary>
        public static string ExtractIntroFingerprintTask_Description_Extracts_intro_fingerprint_from_episodes {
            get {
                return ResourceManager.GetString("ExtractIntroFingerprintTask_Description_Extracts_intro_fingerprint_from_episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract Intro Fingerprint 的本地化字符串。
        /// </summary>
        public static string ExtractIntroFingerprintTask_Name_Extract_Intro_Fingerprint {
            get {
                return ResourceManager.GetString("ExtractIntroFingerprintTask_Name_Extract_Intro_Fingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracts media info from videos and audios, and image capture 的本地化字符串。
        /// </summary>
        public static string ExtractMediaInfoTask_Description_Extracts_media_info_from_videos_and_audios {
            get {
                return ResourceManager.GetString("ExtractMediaInfoTask_Description_Extracts_media_info_from_videos_and_audios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract MediaInfo 的本地化字符串。
        /// </summary>
        public static string ExtractMediaInfoTask_Name_Extract_MediaInfo {
            get {
                return ResourceManager.GetString("ExtractMediaInfoTask_Name_Extract_MediaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract video thumbnail preview and chatper images 的本地化字符串。
        /// </summary>
        public static string ExtractVideoThumbnailTask_Description_Extract_video_thumbnail_preview {
            get {
                return ResourceManager.GetString("ExtractVideoThumbnailTask_Description_Extract_video_thumbnail_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ❤️Favorites 的本地化字符串。
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Catchup Task Scope 的本地化字符串。
        /// </summary>
        public static string GeneralOptions_CatchupScope_Catchup_Scope {
            get {
                return ResourceManager.GetString("GeneralOptions_CatchupScope_Catchup_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applicable to single thread mode. It must be between 0 and 60. Default is 0. 的本地化字符串。
        /// </summary>
        public static string GeneralOptions_CooldownDurationSeconds_Applicable_to_single_thread_mode__Default_is_0_ {
            get {
                return ResourceManager.GetString("GeneralOptions_CooldownDurationSeconds_Applicable_to_single_thread_mode__Default_" +
                        "is_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master Cooldown Duration (Seconds) 的本地化字符串。
        /// </summary>
        public static string GeneralOptions_CooldownSeconds_Cooldown_Time__Seconds___Default_is_0 {
            get {
                return ResourceManager.GetString("GeneralOptions_CooldownSeconds_Cooldown_Time__Seconds___Default_is_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string GeneralOptions_EditorTitle_General_Options {
            get {
                return ResourceManager.GetString("GeneralOptions_EditorTitle_General_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 While library scan, auto merge movies and series to multi versions, bypass naming convention. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string GeneralOptions_MergeMultiVersion_Auto_merge_multiple_versions_if_in_the_same_folder_ {
            get {
                return ResourceManager.GetString("GeneralOptions_MergeMultiVersion_Auto_merge_multiple_versions_if_in_the_same_fold" +
                        "er_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Merge Multi-version 的本地化字符串。
        /// </summary>
        public static string GeneralOptions_MergeMultiVersion_Merge_Multiple_Versions {
            get {
                return ResourceManager.GetString("GeneralOptions_MergeMultiVersion_Merge_Multiple_Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shared by refreshing persons, episodes, external subtitles, local processing tasks, etc. It must be between 1 to 20. Default is 1. 的本地化字符串。
        /// </summary>
        public static string GeneralOptions_Tier2MaxConcurrentCount_Refresh_metadata__subtitle__local_tasks__Default_is_1_ {
            get {
                return ResourceManager.GetString("GeneralOptions_Tier2MaxConcurrentCount_Refresh_metadata__subtitle__local_tasks__D" +
                        "efault_is_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tier 2 Max Concurrent Thread Count 的本地化字符串。
        /// </summary>
        public static string GeneralOptions_Tier2MaxConcurrentCount_Tier_2_Max_Concurrent_Count {
            get {
                return ResourceManager.GetString("GeneralOptions_Tier2MaxConcurrentCount_Tier_2_Max_Concurrent_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Actor Only 的本地化字符串。
        /// </summary>
        public static string HidePersonOption_ActorOnly_ActorOnly {
            get {
                return ResourceManager.GetString("HidePersonOption_ActorOnly_ActorOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Image Person 的本地化字符串。
        /// </summary>
        public static string HidePersonOption_NoImage_NoImage {
            get {
                return ResourceManager.GetString("HidePersonOption_NoImage_NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Built-in Intro Detection Enhanced is not enabled. IntroFingerprintExtract task aborted. 的本地化字符串。
        /// </summary>
        public static string IntroDetectionEnhancedNotEnabled {
            get {
                return ResourceManager.GetString("IntroDetectionEnhancedNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset operation overwrites intro markers added by built-in intro detection 的本地化字符串。
        /// </summary>
        public static string IntroSkipControl_ResetAndOverwrite_ResetAndOverwrite {
            get {
                return ResourceManager.GetString("IntroSkipControl_ResetAndOverwrite_ResetAndOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of Series Id or Season Id separated by comma or semicolon. Default is EMPTY. 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_BlacklistShows_List_of_Series_Id_or_Season_Id_separated_by_comma_or_semicolon__Default_is_EMPTY {
            get {
                return ResourceManager.GetString("IntroSkipOptions_BlacklistShows_List_of_Series_Id_or_Season_Id_separated_by_comma" +
                        "_or_semicolon__Default_is_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional Blacklist 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_BlacklistShows_Optional_Blacklist_Shows {
            get {
                return ResourceManager.GetString("IntroSkipOptions_BlacklistShows_Optional_Blacklist_Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client name keywords separated by comma or semicolon. Detection via 3rd-party clients might not work properly. Default is Emby,Infuse,SenPlayer 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_ClientScope_Allowed_clients__Default_is_Emby_Infuse_SenPlayer {
            get {
                return ResourceManager.GetString("IntroSkipOptions_ClientScope_Allowed_clients__Default_is_Emby_Infuse_SenPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allowed Clients 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_ClientScope_Client_Scope {
            get {
                return ResourceManager.GetString("IntroSkipOptions_ClientScope_Client_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intro Detection Fingerprint Length (Minute) 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_IntroDetectionFingerprintMinutes_Intro_Detection_Fingerprint_Minutes {
            get {
                return ResourceManager.GetString("IntroSkipOptions_IntroDetectionFingerprintMinutes_Intro_Detection_Fingerprint_Min" +
                        "utes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize intro detection fingerprint length. It must be between 2 and 20. Default is 10. 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_IntroDetectionFingerprintMinutes_It_must_be_between_2_and_20__Default_is_10_ {
            get {
                return ResourceManager.GetString("IntroSkipOptions_IntroDetectionFingerprintMinutes_It_must_be_between_2_and_20__De" +
                        "fault_is_10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional Preferences 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_IntroSkipPreferences_IntroSkip_Preferences {
            get {
                return ResourceManager.GetString("IntroSkipOptions_IntroSkipPreferences_IntroSkip_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library Scope 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_LibraryScope_Library_Scope {
            get {
                return ResourceManager.GetString("IntroSkipOptions_LibraryScope_Library_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TV shows library scope to detect. Blank includes all TV shows libraries. 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_LibraryScope_TV_shows_library_scope_to_detect__Blank_includes_all_ {
            get {
                return ResourceManager.GetString("IntroSkipOptions_LibraryScope_TV_shows_library_scope_to_detect__Blank_includes_al" +
                        "l_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library scope to extract fingerprint. Blank includes all libraries with intro detection enabled. Favorites is single selection only 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_MarkerEnabledLibraryScope_Intro_detection_enabled_library_scope__Blank_includes_all_ {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MarkerEnabledLibraryScope_Intro_detection_enabled_library_scope_" +
                        "_Blank_includes_all_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library Scope 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_MarkerEnabledLibraryScope_Library_Scope {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MarkerEnabledLibraryScope_Library_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Credits Duration (Seconds), Default is 360 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_MaxCreditsDurationSeconds {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MaxCreditsDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Intro Duration (Seconds), Default is 150 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_MaxIntroDurationSeconds {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MaxIntroDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min Opening Plot Duration (Seconds), Default is 60 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_MinOpeningPlotDurationSeconds {
            get {
                return ResourceManager.GetString("IntroSkipOptions_MinOpeningPlotDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Built-in Intro Detection Enhanced 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_UnlockIntroSkip_Built_in_Intro_Skip_Enhanced {
            get {
                return ResourceManager.GetString("IntroSkipOptions_UnlockIntroSkip_Built_in_Intro_Skip_Enhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provide customizable options, unlock Strm support. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_UnlockIntroSkip_Unlock_Strm_support_for_built_in_intro_skip_detection {
            get {
                return ResourceManager.GetString("IntroSkipOptions_UnlockIntroSkip_Unlock_Strm_support_for_built_in_intro_skip_dete" +
                        "ction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allowed Users 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_UserScope_User_Scope {
            get {
                return ResourceManager.GetString("IntroSkipOptions_UserScope_User_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users allowed to detect. Blank includes all users. 的本地化字符串。
        /// </summary>
        public static string IntroSkipOptions_UserScope_Users_allowed_to_detect__Blank_includes_all {
            get {
                return ResourceManager.GetString("IntroSkipOptions_UserScope_Users_allowed_to_detect__Blank_includes_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No detection but pause operation to set intro and/or credits markers 的本地化字符串。
        /// </summary>
        public static string IntroSkipPreference_NoDetectionButReset_NoDetectionButReset {
            get {
                return ResourceManager.GetString("IntroSkipPreference_NoDetectionButReset_NoDetectionButReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternative MovieDb Api Key is invalid 的本地化字符串。
        /// </summary>
        public static string InvalidAltMovieDbApiKey {
            get {
                return ResourceManager.GetString("InvalidAltMovieDbApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternative MovieDb Api Url is invalid 的本地化字符串。
        /// </summary>
        public static string InvalidAltMovieDbApiUrl {
            get {
                return ResourceManager.GetString("InvalidAltMovieDbApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternative MovieDb Image Url is invalid 的本地化字符串。
        /// </summary>
        public static string InvalidAltMovieDbImageUrl {
            get {
                return ResourceManager.GetString("InvalidAltMovieDbImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fingerprint catchup is invalid because built-in intro detection enhanced is not enabled. 的本地化字符串。
        /// </summary>
        public static string InvalidFingerprintCatchup {
            get {
                return ResourceManager.GetString("InvalidFingerprintCatchup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None of TV show libraries has intro detection enabled. Favorites is invalid. 的本地化字符串。
        /// </summary>
        public static string InvalidMarkerEnabledLibraryScope {
            get {
                return ResourceManager.GetString("InvalidMarkerEnabledLibraryScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Server is invalid. Format is http[s]://[&lt;username&gt;:&lt;password&gt;@]&lt;host&gt;:&lt;port&gt; 的本地化字符串。
        /// </summary>
        public static string InvalidProxyServer {
            get {
                return ResourceManager.GetString("InvalidProxyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TV show or season ID is invalid: {0} 的本地化字符串。
        /// </summary>
        public static string InvalidShowSeasonIds {
            get {
                return ResourceManager.GetString("InvalidShowSeasonIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 书籍 的本地化字符串。
        /// </summary>
        public static string ItemType_Book_Book {
            get {
                return ResourceManager.GetString("ItemType_Book_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合集 的本地化字符串。
        /// </summary>
        public static string ItemType_Collection_Collection {
            get {
                return ResourceManager.GetString("ItemType_Collection_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集 的本地化字符串。
        /// </summary>
        public static string ItemType_Episode_Episode {
            get {
                return ResourceManager.GetString("ItemType_Episode_Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 的本地化字符串。
        /// </summary>
        public static string ItemType_Game_Game {
            get {
                return ResourceManager.GetString("ItemType_Game_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流派 的本地化字符串。
        /// </summary>
        public static string ItemType_Genre_Genre {
            get {
                return ResourceManager.GetString("ItemType_Genre_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电视直播 的本地化字符串。
        /// </summary>
        public static string ItemType_LiveTv_LiveTv {
            get {
                return ResourceManager.GetString("ItemType_LiveTv_LiveTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电影 的本地化字符串。
        /// </summary>
        public static string ItemType_Movie_Movie {
            get {
                return ResourceManager.GetString("ItemType_Movie_Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐 的本地化字符串。
        /// </summary>
        public static string ItemType_Music_Music {
            get {
                return ResourceManager.GetString("ItemType_Music_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专辑 的本地化字符串。
        /// </summary>
        public static string ItemType_MusicAlbum_MusicAlbum {
            get {
                return ResourceManager.GetString("ItemType_MusicAlbum_MusicAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music Artist 的本地化字符串。
        /// </summary>
        public static string ItemType_MusicArtist_MusicArtist {
            get {
                return ResourceManager.GetString("ItemType_MusicArtist_MusicArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人物 的本地化字符串。
        /// </summary>
        public static string ItemType_Person_Person {
            get {
                return ResourceManager.GetString("ItemType_Person_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片 的本地化字符串。
        /// </summary>
        public static string ItemType_Photo_Photo {
            get {
                return ResourceManager.GetString("ItemType_Photo_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相册 的本地化字符串。
        /// </summary>
        public static string ItemType_PhotoAlbum_PhotoAlbum {
            get {
                return ResourceManager.GetString("ItemType_PhotoAlbum_PhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放列表 的本地化字符串。
        /// </summary>
        public static string ItemType_Playlist_Playlist {
            get {
                return ResourceManager.GetString("ItemType_Playlist_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Season 的本地化字符串。
        /// </summary>
        public static string ItemType_Season_Season {
            get {
                return ResourceManager.GetString("ItemType_Season_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电视节目 的本地化字符串。
        /// </summary>
        public static string ItemType_Series_Series {
            get {
                return ResourceManager.GetString("ItemType_Series_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作室 的本地化字符串。
        /// </summary>
        public static string ItemType_Studio_Studio {
            get {
                return ResourceManager.GetString("ItemType_Studio_Studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        public static string ItemType_Tag_Tag {
            get {
                return ResourceManager.GetString("ItemType_Tag_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预告片 的本地化字符串。
        /// </summary>
        public static string ItemType_Trailer_Trailer {
            get {
                return ResourceManager.GetString("ItemType_Trailer_Trailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video 的本地化字符串。
        /// </summary>
        public static string ItemType_Video_Video {
            get {
                return ResourceManager.GetString("ItemType_Video_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional Exclusive Extract Feature Control 的本地化字符串。
        /// </summary>
        public static string MediaInfoExtractOptions_ExclusiveExtractFeatureControl_Exclusive_Extract_Feature_Control {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_ExclusiveExtractFeatureControl_Exclusive_Extract_Feature_" +
                        "Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize Image Capture Position 的本地化字符串。
        /// </summary>
        public static string MediaInfoExtractOptions_ImageCaptureOffset_Image_Capture_Offset {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_ImageCaptureOffset_Image_Capture_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image capture offset as a percentage of runtime. It must be between 10 and 90. Default is 10. 的本地化字符串。
        /// </summary>
        public static string MediaInfoExtractOptions_ImageCaptureOffset_Image_capture_position_as_a_percentage_of_runtime__Default_is_10_ {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_ImageCaptureOffset_Image_capture_position_as_a_percentage" +
                        "_of_runtime__Default_is_10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional MediaInfo JSON Root Folder 的本地化字符串。
        /// </summary>
        public static string MediaInfoExtractOptions_MediaInfoJsonRootFolder_MediaInfo_Json_Root_Folder {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_MediaInfoJsonRootFolder_MediaInfo_Json_Root_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store or load media info JSON files under this root folder. Default is EMPTY. 的本地化字符串。
        /// </summary>
        public static string MediaInfoExtractOptions_MediaInfoJsonRootFolder_Store_or_load_media_info_JSON_files_under_this_root_folder__Default_is_EMPTY_ {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_MediaInfoJsonRootFolder_Store_or_load_media_info_JSON_fil" +
                        "es_under_this_root_folder__Default_is_EMPTY_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MediaInfo Restore Mode 的本地化字符串。
        /// </summary>
        public static string MediaInfoExtractOptions_MediaInfoRestoreMode_MediaInfo_Restore_Mode {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_MediaInfoRestoreMode_MediaInfo_Restore_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only restore media info, chapter markers, and video thumbnails from JSON or BIF, skipping extraction. 的本地化字符串。
        /// </summary>
        public static string MediaInfoExtractOptions_MediaInfoRestoreMode_Only_restore_media_info__chapters__and_video_thumbnails_from_JSON_or_BIF__skipping_extraction__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_MediaInfoRestoreMode_Only_restore_media_info__chapters__a" +
                        "nd_video_thumbnails_from_JSON_or_BIF__skipping_extraction__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store or load media info and chapters to/from JSON file and also restore video thumbnail BIF. 的本地化字符串。
        /// </summary>
        public static string MediaInfoExtractOptions_PersistMediaInfo_Persist_media_info_in_JSON_file__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_PersistMediaInfo_Persist_media_info_in_JSON_file__Default" +
                        "_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MediaInfo Persist 的本地化字符串。
        /// </summary>
        public static string MediaInfoExtractOptions_PersistMediaInfo_Persist_MediaInfo {
            get {
                return ResourceManager.GetString("MediaInfoExtractOptions_PersistMediaInfo_Persist_MediaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge movies and series per library or across libraries, triggered post library scan 的本地化字符串。
        /// </summary>
        public static string MergeMovieTask_Description_Merge_movies_per_library_or_across_libraries_per_preference {
            get {
                return ResourceManager.GetString("MergeMovieTask_Description_Merge_movies_per_library_or_across_libraries_per_prefe" +
                        "rence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder Scope 的本地化字符串。
        /// </summary>
        public static string MergeScopeOption_FolderScope_FolderScope {
            get {
                return ResourceManager.GetString("MergeScopeOption_FolderScope_FolderScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Scope 的本地化字符串。
        /// </summary>
        public static string MergeScopeOption_GlobalScope_GlobalScope {
            get {
                return ResourceManager.GetString("MergeScopeOption_GlobalScope_GlobalScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library Scope 的本地化字符串。
        /// </summary>
        public static string MergeScopeOption_LibraryScope_LibraryScope {
            get {
                return ResourceManager.GetString("MergeScopeOption_LibraryScope_LibraryScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternative MovieDb Api Key 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbApiKey_Alternative_MovieDb_Api_Key {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbApiKey_Alternative_MovieDb_Api_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provide your own Api Key. Blank uses system default. 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbApiKey_Provide_your_own_MovieDb_Api_Key__Blank_uses_system_default_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbApiKey_Provide_your_own_MovieDb_Api_Key__Blank_u" +
                        "ses_system_default_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternative MovieDb Api Url 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbApiUrl_Alternative_MovieDb_Api_Url {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbApiUrl_Alternative_MovieDb_Api_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default alternative URL is https://api.tmdb.org Blank uses system default https://api.themoviedb.org 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbApiUrl_Default_alternative_is_https___api_tmdb_org {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbApiUrl_Default_alternative_is_https___api_tmdb_o" +
                        "rg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternative MovieDb Image Url 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbImageUrl_Alternative_MovieDb_Image_Url {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbImageUrl_Alternative_MovieDb_Image_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provide your own alternative Url. Blank uses system default https://image.tmdb.org 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_AltMovieDbImageUrl_No_default_alternative__Provide_by_yourself_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_AltMovieDbImageUrl_No_default_alternative__Provide_by_your" +
                        "self_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block English such non fallback language for movie, series, season and episode overview. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_BlockNonFallbackLanguage_Block_English_such_non_fallback_language_in_overview__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_BlockNonFallbackLanguage_Block_English_such_non_fallback_l" +
                        "anguage_in_overview__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block Non Fallback Language Overview 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_BlockNonFallbackLanguage_Block_Non_Fallback_Language {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_BlockNonFallbackLanguage_Block_Non_Fallback_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize Tvdb Fallback Language 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_ChineseTvdb_Customize_Tvdb_Fallback_Language {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_ChineseTvdb_Customize_Tvdb_Fallback_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to get Chinese or Japanese metadata from Tvdb. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_ChineseTvdb_Try_to_get_Chinese_or_Japanese_metadata_from_Tvdb__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_ChineseTvdb_Try_to_get_Chinese_or_Japanese_metadata_from_T" +
                        "vdb__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Alternative MovieDb Config 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_EnableAltMovieDbUrl {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EnableAltMovieDbUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enhance MovieDb Person 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_EnhanceMovieDbPerson_Enhance_MovieDb_Person {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EnhanceMovieDbPerson_Enhance_MovieDb_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract also_known_as while running refresh person scheduled task, import season cast, update series cast. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_EnhanceMovieDbPerson_Import_season_cast_and_update_series_people__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EnhanceMovieDbPerson_Import_season_cast_and_update_series_" +
                        "people__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add support to import actor image URL from Nfo. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_EnhanceNfoMetadata_Add_support_to_import_actor_image_url__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EnhanceNfoMetadata_Add_support_to_import_actor_image_url__" +
                        "Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nfo Metadata Import Enhanced 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_EnhanceNfoMetadata_Nfo_Metadata_Import_Enhanced {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EnhanceNfoMetadata_Nfo_Metadata_Import_Enhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Episode metadata refresh lookback days for scheduled task. Default is 365 days. 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_EpisodeRefreshLookbackDays_Episode_metadata_refresh_lookback_days__Default_is_365_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EpisodeRefreshLookbackDays_Episode_metadata_refresh_lookba" +
                        "ck_days__Default_is_365_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Episode Refresh Lookback Days 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_EpisodeRefreshLookBackDays_Episode_Refresh_Lookback_Days {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EpisodeRefreshLookBackDays_Episode_Refresh_Lookback_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Episode Refresh Scope 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_EpisodeRefreshScope_Episode_Metadata_Refresh_Scope {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EpisodeRefreshScope_Episode_Metadata_Refresh_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Episode metadata refresh scope for scheduled task and catch-up across all TV show libraries. Default is No Overview and No Image. 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_EpisodeRefreshScope_Episode_refresh_scope_for_scheduled_task_and_catch_up__Default_is_no_overview_and_no_image_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_EpisodeRefreshScope_Episode_refresh_scope_for_scheduled_ta" +
                        "sk_and_catch_up__Default_is_no_overview_and_no_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Local Episode Group 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_LocalEpisodeGroup_Local_Episode_Group {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_LocalEpisodeGroup_Local_Episode_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store or load episode group info to/from JSON file. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_LocalEpisodeGroup_Store_or_load_episode_group_info_to_from_JSON_file__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_LocalEpisodeGroup_Store_or_load_episode_group_info_to_from" +
                        "_JSON_file__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support MovieDb Episode Group 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_MovieDbEpisodeGroup_Support_MovieDb_Episode_Group {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_MovieDbEpisodeGroup_Support_MovieDb_Episode_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scrape TV show by specified episode group. Support external source. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string MetadataEnhanceOptions_MovieDbEpisodeGroup_Support_MovieDb_episode_group_scrapping_for_TV_shows__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("MetadataEnhanceOptions_MovieDbEpisodeGroup_Support_MovieDb_episode_group_scrappin" +
                        "g_for_TV_shows__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize MovieDb Fallback Language 的本地化字符串。
        /// </summary>
        public static string ModOptions_ChineseMovieDb_Chinese_MovieDb {
            get {
                return ResourceManager.GetString("ModOptions_ChineseMovieDb_Chinese_MovieDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try to get Chinese or Japanese metadata from MovieDb. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string ModOptions_ChineseMovieDb_Optimize_MovieDb_for_Chinese_metadata__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_ChineseMovieDb_Optimize_MovieDb_for_Chinese_metadata__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Search Enhanced 的本地化字符串。
        /// </summary>
        public static string ModOptions_EnhanceChineseSearch_Enhance_Chinese_Search {
            get {
                return ResourceManager.GetString("ModOptions_EnhanceChineseSearch_Enhance_Chinese_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support Chinese fuzzy search and Pinyin search. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string ModOptions_EnhanceChineseSearch_Support_Chinese_fuzzy_search_and_Pinyin_search__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_EnhanceChineseSearch_Support_Chinese_fuzzy_search_and_Pinyin_search__D" +
                        "efault_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude Original Title 的本地化字符串。
        /// </summary>
        public static string ModOptions_ExcludeOriginalTitle_Exclude_Original_Title {
            get {
                return ResourceManager.GetString("ModOptions_ExcludeOriginalTitle_Exclude_Original_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude original title from search. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string ModOptions_ExcludeOriginalTitle_Exclude_original_title_from_search__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_ExcludeOriginalTitle_Exclude_original_title_from_search__Default_is_OF" +
                        "F_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclusive MediaInfo Extract 的本地化字符串。
        /// </summary>
        public static string ModOptions_ExclusiveExtract_Exclusive_Extract {
            get {
                return ResourceManager.GetString("ModOptions_ExclusiveExtract_Exclusive_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Take over media info extract (ffprobe) and image capture (ffmpeg) for all libraries. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string ModOptions_ExclusiveExtract_Only_allow_this_plugin_to_extract_media_info__ffprobe__and_capture_image__ffmpeg___Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_ExclusiveExtract_Only_allow_this_plugin_to_extract_media_info__ffprobe" +
                        "__and_capture_image__ffmpeg___Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fallback Languages 的本地化字符串。
        /// </summary>
        public static string ModOptions_FallbackLanguages_Fallback_Languages {
            get {
                return ResourceManager.GetString("ModOptions_FallbackLanguages_Fallback_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fallback metadata languages, prioritized from left to right. 的本地化字符串。
        /// </summary>
        public static string ModOptions_FallbackLanguages_Fallback_languages__Default_is_zh_SG_ {
            get {
                return ResourceManager.GetString("ModOptions_FallbackLanguages_Fallback_languages__Default_is_zh_SG_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Cast and Crew by Preference 的本地化字符串。
        /// </summary>
        public static string ModOptions_HidePersonNoImage_Hide_Person_without_Image {
            get {
                return ResourceManager.GetString("ModOptions_HidePersonNoImage_Hide_Person_without_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide cast and crew based on your preferences. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string ModOptions_HidePersonNoImage_Hide_person_without_image__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_HidePersonNoImage_Hide_person_without_image__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Language Poster 的本地化字符串。
        /// </summary>
        public static string ModOptions_OriginalPoster_Original_Poster {
            get {
                return ResourceManager.GetString("ModOptions_OriginalPoster_Original_Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prefer original poster based on the original language. Support TMDB, TVDB and FANART. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string ModOptions_OriginalPoster_Show_original_poster_based_on_original_language__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_OriginalPoster_Show_original_poster_based_on_original_language__Defaul" +
                        "t_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto generate pinyin initials as sort title. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string ModOptions_PinyinSortName_Auto_generate_pinyin_initials_as_sort_title {
            get {
                return ResourceManager.GetString("ModOptions_PinyinSortName_Auto_generate_pinyin_initials_as_sort_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pinyin Initials Sort Title 的本地化字符串。
        /// </summary>
        public static string ModOptions_PinyinSortName_Pinyin_Sort_Title {
            get {
                return ResourceManager.GetString("ModOptions_PinyinSortName_Pinyin_Sort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support http(s) proxy server. Latency to Google must be less than 999 milliseconds. Disabled if unavailabe or leave blank. Restart if any changes. 的本地化字符串。
        /// </summary>
        public static string ModOptions_ProxyServer_Enable_http_proxy_server__Blank_is_OFF_ {
            get {
                return ResourceManager.GetString("ModOptions_ProxyServer_Enable_http_proxy_server__Blank_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Server 的本地化字符串。
        /// </summary>
        public static string ModOptions_ProxyServer_Proxy_Server {
            get {
                return ResourceManager.GetString("ModOptions_ProxyServer_Proxy_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include search item types. Default is Movie, Collection, Series. Blank includes all. 的本地化字符串。
        /// </summary>
        public static string ModOptions_SearchScope_Include_item_types__Blank_includes_all_ {
            get {
                return ResourceManager.GetString("ModOptions_SearchScope_Include_item_types__Blank_includes_all_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Scope 的本地化字符串。
        /// </summary>
        public static string ModOptions_SearchScope_Search_Scope {
            get {
                return ResourceManager.GetString("ModOptions_SearchScope_Search_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network 的本地化字符串。
        /// </summary>
        public static string NetworkOptions_EditorTitle_Network {
            get {
                return ResourceManager.GetString("NetworkOptions_EditorTitle_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Proxy Server 的本地化字符串。
        /// </summary>
        public static string NetworkOptions_EnableProxyServer_Enable_Proxy_Server {
            get {
                return ResourceManager.GetString("NetworkOptions_EnableProxyServer_Enable_Proxy_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable proxy for server outgoing http requests. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string NetworkOptions_EnableProxyServer_Enable_Proxy_Server__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("NetworkOptions_EnableProxyServer_Enable_Proxy_Server__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Update 的本地化字符串。
        /// </summary>
        public static string No_Update_Message {
            get {
                return ResourceManager.GetString("No_Update_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Catch-up mode update - {0}\n\n{1}&apos;s favorite 的本地化字符串。
        /// </summary>
        public static string Notification_CatchupUpdate_EventDescription {
            get {
                return ResourceManager.GetString("Notification_CatchupUpdate_EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favorites Updated 的本地化字符串。
        /// </summary>
        public static string Notification_CatchupUpdate_EventName {
            get {
                return ResourceManager.GetString("Notification_CatchupUpdate_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - {1} - Credits marker updated\n\nCredits duration: {2}\n\nby {3} 的本地化字符串。
        /// </summary>
        public static string Notification_CreditsUpdate_Description {
            get {
                return ResourceManager.GetString("Notification_CreditsUpdate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - {1} - Credits marker updated 的本地化字符串。
        /// </summary>
        public static string Notification_CreditsUpdate_Message {
            get {
                return ResourceManager.GetString("Notification_CreditsUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Name:\n{0}\n\nItem Path:\n{1}\n\nMount Paths:\n{2} 的本地化字符串。
        /// </summary>
        public static string Notification_DeepDelete_EventDescription {
            get {
                return ResourceManager.GetString("Notification_DeepDelete_EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media Deep Delete 的本地化字符串。
        /// </summary>
        public static string Notification_DeepDelete_EventName {
            get {
                return ResourceManager.GetString("Notification_DeepDelete_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IntroSkip Updated 的本地化字符串。
        /// </summary>
        public static string Notification_IntroSkipUpdate_EventName {
            get {
                return ResourceManager.GetString("Notification_IntroSkipUpdate_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - {1} - Intro marker updated\n\nIntro start time: {2}\nIntro end time: {3}\n\nby {4} 的本地化字符串。
        /// </summary>
        public static string Notification_IntroUpdate_Description {
            get {
                return ResourceManager.GetString("Notification_IntroUpdate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - {1} - Intro marker updated 的本地化字符串。
        /// </summary>
        public static string Notification_IntroUpdate_Message {
            get {
                return ResourceManager.GetString("Notification_IntroUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accept 的本地化字符串。
        /// </summary>
        public static string OKButtonCaption {
            get {
                return ResourceManager.GetString("OKButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation completed successfully 的本地化字符串。
        /// </summary>
        public static string Operation_Success {
            get {
                return ResourceManager.GetString("Operation_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original_Repo_Link 的本地化字符串。
        /// </summary>
        public static string Original_Repo_Link {
            get {
                return ResourceManager.GetString("Original_Repo_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFF 的本地化字符串。
        /// </summary>
        public static string PersistMediaInfoOption_None_None {
            get {
                return ResourceManager.GetString("PersistMediaInfoOption_None_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export media info and chapter markers to JSON files 的本地化字符串。
        /// </summary>
        public static string PersistMediaInfoTask_Description_Persists_media_info_to_json_file {
            get {
                return ResourceManager.GetString("PersistMediaInfoTask_Description_Persists_media_info_to_json_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Persist MediaInfo 的本地化字符串。
        /// </summary>
        public static string PersistMediaInfoTask_Name_Persist_MediaInfo {
            get {
                return ResourceManager.GetString("PersistMediaInfoTask_Name_Persist_MediaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Catch-up Mode 的本地化字符串。
        /// </summary>
        public static string PluginOptions_CatchupMode_Catch_up_Mode__Experimental_ {
            get {
                return ResourceManager.GetString("PluginOptions_CatchupMode_Catch_up_Mode__Experimental_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract media info for newly added items and intro marker detection or sync in near real-time. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string PluginOptions_CatchupMode_Catch_up_users_favorites__exclusive_to_Strm___Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_CatchupMode_Catch_up_users_favorites__exclusive_to_Strm___Default_i" +
                        "s_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strm Assistant 的本地化字符串。
        /// </summary>
        public static string PluginOptions_EditorTitle_Strm_Assistant {
            get {
                return ResourceManager.GetString("PluginOptions_EditorTitle_Strm_Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MediaInfo Extract 的本地化字符串。
        /// </summary>
        public static string PluginOptions_EditorTitle_Strm_Extract {
            get {
                return ResourceManager.GetString("PluginOptions_EditorTitle_Strm_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Capture and Thumbnail Preview Enhanced 的本地化字符串。
        /// </summary>
        public static string PluginOptions_EnableImageCapture_Enable_Image_Capture {
            get {
                return ResourceManager.GetString("PluginOptions_EnableImageCapture_Enable_Image_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock image capture, video thumbnail BIF for Strm. Skip embedded image. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string PluginOptions_EnableImageCapture_Perform_image_capture_for_videos_without_primary_image__Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_EnableImageCapture_Perform_image_capture_for_videos_without_primary" +
                        "_image__Default_is_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adaptive Intro Skip 的本地化字符串。
        /// </summary>
        public static string PluginOptions_EnableIntroSkip_Enable_Intro_Skip__Experimental_ {
            get {
                return ResourceManager.GetString("PluginOptions_EnableIntroSkip_Enable_Intro_Skip__Experimental_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playback behavior-based intro and credits detection for episodes. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string PluginOptions_EnableIntroSkip_Enable_intro_skip_and_credits_skip_for_episodes__Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_EnableIntroSkip_Enable_intro_skip_and_credits_skip_for_episodes__De" +
                        "fault_is_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Additional Part and Extra 的本地化字符串。
        /// </summary>
        public static string PluginOptions_IncludeExtra_Include_Extra {
            get {
                return ResourceManager.GetString("PluginOptions_IncludeExtra_Include_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include additional parts and extras to extract. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string PluginOptions_IncludeExtra_Include_media_extras_to_extract__Default_is_False_ {
            get {
                return ResourceManager.GetString("PluginOptions_IncludeExtra_Include_media_extras_to_extract__Default_is_False_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please uninstall the StrmExtract.dll plugin that duplicates functionality and/or the InfuseSync.dll plugin that has thread-safe issues, and then restart Emby. 的本地化字符串。
        /// </summary>
        public static string PluginOptions_IncompatibleMessage_Please_uninstall_the_conflict_plugin_Strm_Extract {
            get {
                return ResourceManager.GetString("PluginOptions_IncompatibleMessage_Please_uninstall_the_conflict_plugin_Strm_Extra" +
                        "ct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intro and Credits Detection 的本地化字符串。
        /// </summary>
        public static string PluginOptions_IntroSkipOptions_Intro_Credits_Detection {
            get {
                return ResourceManager.GetString("PluginOptions_IntroSkipOptions_Intro_Credits_Detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod failed. Please check log in debug mode after restart to troubleshoot. 的本地化字符串。
        /// </summary>
        public static string PluginOptions_IsHarmonyModFailed_Harmony_Mod_Failed {
            get {
                return ResourceManager.GetString("PluginOptions_IsHarmonyModFailed_Harmony_Mod_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library Scope 的本地化字符串。
        /// </summary>
        public static string PluginOptions_LibraryScope_Library_Scope {
            get {
                return ResourceManager.GetString("PluginOptions_LibraryScope_Library_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library scope to extract. Blank includes all. 的本地化字符串。
        /// </summary>
        public static string PluginOptions_LibraryScope_Library_scope_to_extract__Blank_includes_all_ {
            get {
                return ResourceManager.GetString("PluginOptions_LibraryScope_Library_scope_to_extract__Blank_includes_all_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master Max Concurrent Thread Count 的本地化字符串。
        /// </summary>
        public static string PluginOptions_MaxConcurrentCount_Max_Concurrent_Count {
            get {
                return ResourceManager.GetString("PluginOptions_MaxConcurrentCount_Max_Concurrent_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shared by mediainfo extract, image capture, video thumbnail and fingerprint extract tasks. It must be between 1 to 20. Default is 1. 的本地化字符串。
        /// </summary>
        public static string PluginOptions_MaxConcurrentCount_Max_Concurrent_Count_must_be_between_1_to_10__Default_is_1_ {
            get {
                return ResourceManager.GetString("PluginOptions_MaxConcurrentCount_Max_Concurrent_Count_must_be_between_1_to_10__De" +
                        "fault_is_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata Enhance 的本地化字符串。
        /// </summary>
        public static string PluginOptions_MetadataEnhanceOptions_Metadata_Enhance {
            get {
                return ResourceManager.GetString("PluginOptions_MetadataEnhanceOptions_Metadata_Enhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string PluginOptions_ModOptions_Mod_Features {
            get {
                return ResourceManager.GetString("PluginOptions_ModOptions_Mod_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Strm only. Turn off to support all. Default is ON. 的本地化字符串。
        /// </summary>
        public static string PluginOptions_StrmOnly_Extract_media_info_of_Strm_only__Default_is_True_ {
            get {
                return ResourceManager.GetString("PluginOptions_StrmOnly_Extract_media_info_of_Strm_only__Default_is_True_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strm Only 的本地化字符串。
        /// </summary>
        public static string PluginOptions_StrmOnly_Strm_Only {
            get {
                return ResourceManager.GetString("PluginOptions_StrmOnly_Strm_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available 的本地化字符串。
        /// </summary>
        public static string ProxyServer_Available {
            get {
                return ResourceManager.GetString("ProxyServer_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unavailable 的本地化字符串。
        /// </summary>
        public static string ProxyServer_Unavailable {
            get {
                return ResourceManager.GetString("ProxyServer_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refreshes and repairs Chinese actors 的本地化字符串。
        /// </summary>
        public static string RefreshPersonTask_Description_Refreshes_and_repairs_Chinese_actors {
            get {
                return ResourceManager.GetString("RefreshPersonTask_Description_Refreshes_and_repairs_Chinese_actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Chinese Actor 的本地化字符串。
        /// </summary>
        public static string RefreshPersonTask_Name_Refresh_Chinese_Actor {
            get {
                return ResourceManager.GetString("RefreshPersonTask_Name_Refresh_Chinese_Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repo_Link 的本地化字符串。
        /// </summary>
        public static string Repo_Link {
            get {
                return ResourceManager.GetString("Repo_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scans external subtitles for videos 的本地化字符串。
        /// </summary>
        public static string ScanExternalSubtitleTask_Description_Scans_external_subtitles_for_videos {
            get {
                return ResourceManager.GetString("ScanExternalSubtitleTask_Description_Scans_external_subtitles_for_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan External Subtitles 的本地化字符串。
        /// </summary>
        public static string ScanExternalSubtitleTask_Name_Scan_External_Subtitles {
            get {
                return ResourceManager.GetString("ScanExternalSubtitleTask_Name_Scan_External_Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Preferred Metadata Language is not set to Chinese. RefreshPerson Task Aborted. 的本地化字符串。
        /// </summary>
        public static string ServerPreferredMetadataLanguageIsNotZh {
            get {
                return ResourceManager.GetString("ServerPreferredMetadataLanguageIsNotZh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beautify Title Display 的本地化字符串。
        /// </summary>
        public static string UIFunctionOptions_BeautifyMissingMetadata_Beautify_Missing_Metadata {
            get {
                return ResourceManager.GetString("UIFunctionOptions_BeautifyMissingMetadata_Beautify_Missing_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beautify episode title display with no metadata and additional part title display. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string UIFunctionOptions_BeautifyMissingMetadata_Beautify_missing_metadata_for_episode_display__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("UIFunctionOptions_BeautifyMissingMetadata_Beautify_missing_metadata_for_episode_d" +
                        "isplay__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Functions 的本地化字符串。
        /// </summary>
        public static string UIFunctionOptions_EditorTitle_UI_Functions {
            get {
                return ResourceManager.GetString("UIFunctionOptions_EditorTitle_UI_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enforce Library Order 的本地化字符串。
        /// </summary>
        public static string UIFunctionOptions_EnforceLibraryOrder_Enforce_Library_Order {
            get {
                return ResourceManager.GetString("UIFunctionOptions_EnforceLibraryOrder_Enforce_Library_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enforce customized library order per the first admin. Default if OFF. 的本地化字符串。
        /// </summary>
        public static string UIFunctionOptions_EnforceLibraryOrder_Enforce_library_order_per_the_first_admin__Default_if_OFF_ {
            get {
                return ResourceManager.GetString("UIFunctionOptions_EnforceLibraryOrder_Enforce_library_order_per_the_first_admin__" +
                        "Default_if_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add MovieDb support for the view missing episodes function, support Episode Group. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string UIFunctionOptions_EnhanceMissingEpisodes_Add_MovieDb_support_for_the_missing_episodes_function__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("UIFunctionOptions_EnhanceMissingEpisodes_Add_MovieDb_support_for_the_missing_epis" +
                        "odes_function__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Missing Episodes Enhanced 的本地化字符串。
        /// </summary>
        public static string UIFunctionOptions_EnhanceMissingEpisodes_Missing_Episodes_Enhanced {
            get {
                return ResourceManager.GetString("UIFunctionOptions_EnhanceMissingEpisodes_Missing_Episodes_Enhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide collection library from user views, if removed, prevent auto creation. Default is OFF. 的本地化字符串。
        /// </summary>
        public static string UIFunctionOptions_NoBoxsetsAutoCreation_Prevent_automatic_boxset_library_creation__Default_is_OFF_ {
            get {
                return ResourceManager.GetString("UIFunctionOptions_NoBoxsetsAutoCreation_Prevent_automatic_boxset_library_creation" +
                        "__Default_is_OFF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Collection Library 的本地化字符串。
        /// </summary>
        public static string UIFunctionOptions_NoBoxsetsAutoCreation_Prevent_Boxsets_Auto_Creation {
            get {
                return ResourceManager.GetString("UIFunctionOptions_NoBoxsetsAutoCreation_Prevent_Boxsets_Auto_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Emby won&apos;t work without turning off Chinese Search Enhanced properly. 的本地化字符串。
        /// </summary>
        public static string Uninstall_Warning {
            get {
                return ResourceManager.GetString("Uninstall_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update failed. Check error details in admin dashboard. 的本地化字符串。
        /// </summary>
        public static string Update_Failed_Message {
            get {
                return ResourceManager.GetString("Update_Failed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates plugin to the latest version 的本地化字符串。
        /// </summary>
        public static string UpdatePluginTask_Description_Updates_plugin_to_the_latest_version {
            get {
                return ResourceManager.GetString("UpdatePluginTask_Description_Updates_plugin_to_the_latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Plugin 的本地化字符串。
        /// </summary>
        public static string UpdatePluginTask_Name_Update_Plugin {
            get {
                return ResourceManager.GetString("UpdatePluginTask_Name_Update_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Wiki_Link {
            get {
                return ResourceManager.GetString("Wiki_Link", resourceCulture);
            }
        }
    }
}
