<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <AssemblyVersion>4.9.1.23</AssemblyVersion>
    <FileVersion>4.9.1.23</FileVersion>
    <CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
    <IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Tokenizer\linux\libsimple.so" />
    <None Remove="Tokenizer\win\simple.dll" />
    <None Remove="Web\Resources\strmassistant.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\thumb.png" />
    <EmbeddedResource Include="Tokenizer\linux\libsimple.so" />
    <EmbeddedResource Include="Tokenizer\win\simple.dll" />
    <EmbeddedResource Include="Web\Resources\strmassistant.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CHTCHSConv" Version="1.0.0">
    </PackageReference>
    <PackageReference Include="ILRepack" Version="2.0.44">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Lib.Harmony" Version="2.4.1" />
    <PackageReference Include="mediabrowser.server.core" Version="4.8.11" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Resource.Embedder" Version="2.2.0" />
    <PackageReference Include="SQLitePCL.pretty.core" Version="1.2.2" />
    <PackageReference Include="TinyPinyin" Version="1.1.0">
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.zh-hant.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.zh.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="$(ILRepack) /out:bin\output\$(TargetFileName) $(TargetPath) $(TargetDir)0Harmony.dll $(TargetDir)ChineseConverter.dll $(TargetDir)TinyPinyin.dll /lib:$(TargetDir)" />
  </Target>
</Project>
