<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0</TargetFrameworks>
	  <Version>4.10.0.40</Version>
	  <AssemblyVersion>$(Version)</AssemblyVersion>
	  <FileVersion>$(Version)</FileVersion>
    <CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>

	  <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	  <EnableSourceLink>false</EnableSourceLink>
	  <EnableSourceControlManagerQueries>false</EnableSourceControlManagerQueries>
	  <PublishRepositoryUrl>false</PublishRepositoryUrl>
	  <EmbedUntrackedSources>false</EmbedUntrackedSources>
	  <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>
	  <Deterministic>false</Deterministic>
	  
	<LangVersion>8.0</LangVersion>
	  
	  <RootNamespace>StrmAssistant</RootNamespace>
	  <AssemblyName>StrmAssistant</AssemblyName>
	  
  </PropertyGroup>

	<ItemGroup>
		<None Remove="Resources\Tokenizer\**\*.dll" />
		<None Remove="Resources\Tokenizer\**\*.so" />
		<None Remove="Resources\Tokenizer\**\*.dylib" />
		<None Remove="Web\Resources\strmassistant.js" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Properties\thumb.png" />
		<EmbeddedResource Include="Resources\Tokenizer\**\*.dll" />
		<EmbeddedResource Include="Resources\Tokenizer\**\*.so" />
		<EmbeddedResource Include="Resources\Tokenizer\**\*.dylib" />
		<EmbeddedResource Include="Web\Resources\strmassistant.js" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="..\libs\publicized\Emby.Api.dll">
			<Private>False</Private>
		</Reference>
		<Reference Include="..\libs\publicized\Emby.ProcessRun.dll">
			<Private>False</Private>
		</Reference>
		<Reference Include="..\libs\publicized\Emby.Providers.dll">
			<Private>False</Private>
		</Reference>
		<Reference Include="..\libs\publicized\Emby.Sqlite.dll">
			<Private>False</Private>
		</Reference>
		<Reference Include="MediaBrowser.Controller">
			<HintPath>"..\libs\publicized\MediaBrowser.Controller.dll</HintPath>
		</Reference>
	</ItemGroup>
	
	
  <ItemGroup>
    <PackageReference Include="CHTCHSConv" Version="1.0.0">
    </PackageReference>
    <PackageReference Include="ILRepack" Version="2.0.44">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="mediabrowser.server.core" Version="4.9.1.90" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Resource.Embedder" Version="2.2.0" />
    <PackageReference Include="SQLitePCL.pretty.core" Version="1.2.2" />
    <PackageReference Include="TinyPinyin" Version="1.1.0">
    </PackageReference>
  </ItemGroup>
	
	
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
	
	
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.zh-hant.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.zh.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="$(ILRepack) /out:bin\output\$(TargetFileName) $(TargetPath) $(TargetDir)0Harmony.dll $(TargetDir)ChineseConverter.dll $(TargetDir)TinyPinyin.dll /lib:$(TargetDir)" />
  </Target>
</Project>
